In [35]:
from sklearn.preprocessing import Imputer
I = Imputer(strategy='median')

data = np.array([[1,2,3,np.nan,5],[1,2,3,4,5],\
                 [10,20,30,40,50],[10,20,30,40,50]])
data2 = I.fit_transform(data)
print(data2)

[[ 1.  2.  3. 40.  5.]
 [ 1.  2.  3.  4.  5.]
 [10. 20. 30. 40. 50.]
 [10. 20. 30. 40. 50.]]


/home/wb/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [14]:
from sklearn.metrics import confusion_matrix,\
 precision_score, recall_score

y_true = np.array([2, 0, 2, 2, 0, 1])
y_pred = np.array([0, 0, 2, 2, 0, 2])

p = precision_score(y_true,y_pred,average='macro')
print(p)
score = sum(y_true == y_pred)/len(y_true)
print(score)

confusion_matrix(y_true, y_pred)
    

0.4444444444444444
0.6666666666666666


array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]])

In [4]:
def func():
    print('adfdfdf d df df sadf sdf sdf sdf sadf\
    dfsdfsd sdf sdf sdf sd\
    dfdfsdfsdfsd')

adfdfdf d df df sadf sdf sdf sdf sadf    dfsdfsd sdf sdf sdf sd    dfdfsdfsdfsd
